name: "🔍 Simple Issue"
description: Create a basic feature request ticket
title: "Title"
labels: [
  "feature"
]
projects: [
  "jormunrod/ReservaTuFuturo"
]
body:
  - type: input
    id: activity
    attributes:
      label: "Related Activity"
      description: Mention the activity or project related to this feature
      placeholder: "EDT ID - Activity name"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Provide a brief description of the feature
      placeholder: "Describe the feature request briefly"
    validations:
      required: false
  
    
