issue_template:
  name: Nueva Issue
  about: Plantilla estándar para registrar una issue
  title: "[ISSUE] Título de la Issue"
  labels: []
  assignees: []

  body:
    - type: markdown
      content: |
        ### Título de la Issue
        Describa de forma breve el objetivo de la issue.

    - type: input
      id: titulo
      attributes:
        label: "Título de la Issue"
        description: "Describa el objetivo de la issue"
        placeholder: "Ingrese el título de la issue"

    - type: input
      id: actividad_relacionada
      attributes:
        label: "Actividad relacionada"
        description: "Mencione la actividad o funcionalidad a la que se relaciona esta issue"
        placeholder: "Ejemplo: Login de usuario, Búsqueda, etc."

    - type: textarea
      id: introduccion
      attributes:
        label: "Introducción"
        description: "Proporcione una breve descripción de la issue, incluyendo el contexto y motivos"
        placeholder: "Explica el propósito de esta issue"

    - type: markdown
      content: |
        ### Pasos para completar la issue

    - type: textarea
      id: pasos_para_completar
      attributes:
        label: "Pasos para completar la issue"
        description: "Escriba los pasos necesarios para resolver esta issue"
        placeholder: "1. Describa el primer paso necesario\n2. Detalle el siguiente paso relevante\n3. Continúe con todos los pasos necesarios"

    - type: textarea
      id: informacion_adicional
      attributes:
        label: "Información adicional"
        description: "Agregue cualquier contexto adicional, capturas de pantalla, o enlaces relevantes"
        placeholder: "Información adicional"
