# Generated by Django 5.1.3 on 2024-11-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default=0, max_length=15),
            preserve_default=False,
        ),
    ]
